import React from 'react';
import { Filter, Search, ShieldCheck } from 'lucide-react';
import { CarData, FilterRecommendation } from '../types';
import { motion } from 'motion/react';

interface FilterResultsProps {
  car: CarData;
}

export const FilterResults: React.FC<FilterResultsProps> = ({ car }) => {
  // Mock filter data based on car details
  // In a real app, this would be fetched from an API or generated by AI
  const filters: FilterRecommendation[] = [
    { type: 'Oil', vic: 'C-110', micro: 'T-1636', mann: 'W 68/3', filtron: 'OP 572' },
    { type: 'Air', vic: 'A-1013', micro: 'WA-1342', mann: 'C 24 005', filtron: 'AP 142/1' },
    { type: 'Cabin', vic: 'AC-108', micro: 'R-1345', mann: 'CU 1919', filtron: 'K 1110' },
  ];

  const getFilterIcon = (type: string) => {
    switch (type) {
      case 'Oil': return <div className="w-2 h-2 rounded-full bg-amber-500" />;
      case 'Air': return <div className="w-2 h-2 rounded-full bg-blue-500" />;
      case 'Cabin': return <div className="w-2 h-2 rounded-full bg-green-500" />;
      default: return <div className="w-2 h-2 rounded-full bg-gray-500" />;
    }
  };

  return (
    <div className="flex flex-col gap-4">
      <div className="bg-[var(--tg-theme-secondary-bg-color)] rounded-3xl overflow-hidden border border-black/5 shadow-2xl">
        <div className="bg-gradient-to-r from-zinc-800 to-zinc-900 p-4 flex items-center justify-between text-white">
          <div className="flex items-center gap-2">
            <Filter size={18} />
            <h3 className="font-black text-xs uppercase tracking-[0.2em]">Подбор фильтров</h3>
          </div>
          <Search size={18} className="opacity-50" />
        </div>
        
        <div className="overflow-x-auto">
          <table className="w-full text-left text-[11px] border-collapse">
            <thead>
              <tr className="bg-black/5">
                <th className="p-4 font-black uppercase tracking-widest opacity-30">Тип</th>
                <th className="p-4 font-black uppercase tracking-widest opacity-30">VIC / Micro</th>
                <th className="p-4 font-black uppercase tracking-widest opacity-30 text-right">MANN / Filtron</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-black/5">
              {filters.map((f, i) => (
                <motion.tr 
                  key={i} 
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: i * 0.1 }}
                  className="active:bg-black/5 transition-colors"
                >
                  <td className="p-4">
                    <div className="flex items-center gap-2">
                      {getFilterIcon(f.type)}
                      <div className="font-black uppercase tracking-tight">
                        {f.type === 'Oil' ? 'Масляный' : f.type === 'Air' ? 'Воздушный' : 'Салонный'}
                      </div>
                    </div>
                  </td>
                  <td className="p-4">
                    <div className="flex flex-col gap-1">
                      <span className="font-bold text-[var(--tg-theme-button-color)]">{f.vic}</span>
                      <span className="opacity-40 text-[9px]">{f.micro}</span>
                    </div>
                  </td>
                  <td className="p-4 text-right">
                    <div className="flex flex-col gap-1">
                      <span className="font-bold">{f.mann}</span>
                      <span className="opacity-40 text-[9px]">{f.filtron}</span>
                    </div>
                  </td>
                </motion.tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      <div className="bg-zinc-100 p-3 rounded-2xl border border-black/5 flex items-start gap-3">
        <ShieldCheck size={16} className="text-zinc-400 shrink-0 mt-0.5" />
        <p className="text-[10px] opacity-50 font-medium leading-tight">
          Мы подобрали лучшие аналоги от мировых лидеров: <b>VIC</b> и <b>Micro</b> (Япония), <b>MANN</b> (Германия) и <b>Filtron</b> (Польша).
        </p>
      </div>
    </div>
  );
};
